name: Build and Deploy All MARP Presentations

on:
  push:
    paths:
      - 'b-UnitesEnseignement/Support/*.md'  
      - 'b-UnitesEnseignement/Support/img/**'  
      - 'b-UnitesEnseignement/Exercices/*.pdf'  
  pull_request:
    paths:
      - 'b-UnitesEnseignement/Support/*.md'
      - 'b-UnitesEnseignement/Support/img/**'
      - 'b-UnitesEnseignement/Exercices/*.pdf'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js and MARP CLI
        run: |
          npm install -g @marp-team/marp-cli
          npm install puppeteer

      - name: Generate Presentations (HTML + PDF) and Copy Resources
        run: |
          echo "✅ Création des dossiers..."
          mkdir -p public/img
          mkdir -p public/exercices

          echo "🔍 Vérification des fichiers avant la copie..."
          ls -l b-UnitesEnseignement/Support/img/ || echo "📂 Aucune image trouvée"
          ls -l b-UnitesEnseignement/Exercices/ || echo "📂 Aucun exercice trouvé"

          echo "📂 Copie des images..."
          cp -r b-UnitesEnseignement/Support/img/* public/img/ 2>/dev/null || echo "⚠️ Aucune image copiée"

          echo "📂 Copie des exercices PDF..."
          cp b-UnitesEnseignement/Exercices/*.pdf public/exercices/ 2>/dev/null || echo "⚠️ Aucun exercice PDF copié"

          echo "✅ Contenu final de public/"
          ls -l public/
          ls -l public/exercices/

          echo "<!DOCTYPE html>
          <html lang='fr'>
          <head>
            <meta charset='UTF-8'>
            <meta name='viewport' content='width=device-width, initial-scale=1.0'>
            <title>Liste des Présentations</title>
            <script src='https://cdn.tailwindcss.com'></script>
          </head>
          <body class='bg-gray-900 text-white font-sans p-6'>
            <div class='max-w-4xl mx-auto'>
              <h1 class='text-3xl font-bold mb-4 text-center'>Liste des Présentations</h1>
              <ul class='space-y-3'>" > public/index.html

          for file in b-UnitesEnseignement/Support/*.md; do
            filename=$(basename "$file" .md)

            marp "$file" --html --allow-local-files --output "public/${filename}.html"
            marp "$file" --pdf --allow-local-files --output "public/${filename}.pdf"

            echo "<li class='bg-gray-800 p-4 rounded-lg'>
                    <a href='${filename}.html' class='text-blue-400 hover:underline font-bold'>📄 ${filename} (HTML)</a> |
                    <a href='${filename}.pdf' class='text-green-400 hover:underline font-bold'>📕 ${filename} (PDF)</a>
                  </li>" >> public/index.html
          done

          echo "</ul>" >> public/index.html

          # Ajout de la section "Liste des Exercices"
          echo "<h2 class='text-2xl font-bold mt-8 text-center'>Liste des Exercices</h2>
                <ul class='space-y-3'>" >> public/index.html

          for file in public/exercices/*.pdf; do
            filename=$(basename "$file")

            echo "<li class='bg-gray-800 p-4 rounded-lg'>
                    <a href='exercices/${filename}' class='text-yellow-400 hover:underline font-bold'>📘 ${filename} (PDF)</a>
                  </li>" >> public/index.html
          done

          echo "</ul>
                <p class='mt-6 text-center text-sm text-gray-400'>Généré automatiquement avec MARP et TailwindCSS</p>
                </div>
              </body>
            </html>" >> public/index.html

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
